version: "2.1"

services:

  xbackbone:
    image: lscr.io/linuxserver/xbackbone
    container_name: xbackbone
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config/php/php-local.ini:/config/php/php-local.ini
    ports:
      - "8200:80"
      - "8443:443"
    restart: unless-stopped
